# Generated by Django 3.1 on 2020-12-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobikeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioMobike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
